export const users = [
  {
    id: 1,
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '987-654-3210',
    role: 'Admin',
    address: '1234, MG Road, New Delhi, India',
  },
  {
    id: 2,
    name: 'Isha Verma',
    email: 'isha.verma@example.com',
    phone: '876-543-2109',
    role: 'Sub Admin',
    address: '5678, Residency Road, Bengaluru, India',
  },
  {
    id: 3,
    name: 'Rohit Singh',
    email: 'rohit.singh@example.com',
    phone: '765-432-1098',
    role: 'Manager',
    address: '9101, Park Street, Kolkata, India',
  },
  {
    id: 4,
    name: 'Kavya Patel',
    email: 'kavya.patel@example.com',
    phone: '654-321-0987',
    role: 'Manager',
    address: '2345, Ashram Road, Ahmedabad, India',
  },
  {
    id: 5,
    name: 'Vivaan Desai',
    email: 'vivaan.desai@example.com',
    phone: '543-210-9876',
    role: 'Admin',
    address: '3456, Marine Drive, Mumbai, India',
  },
  {
    id: 6,
    name: 'Ananya Nair',
    email: 'ananya.nair@example.com',
    phone: '432-109-8765',
    role: 'Sub Admin',
    address: '4567, Palace Road, Mysuru, India',
  },
  {
    id: 7,
    name: 'Aryan Reddy',
    email: 'aryan.reddy@example.com',
    phone: '321-098-7654',
    role: 'Manager',
    address: '5678, Necklace Road, Hyderabad, India',
  },
  {
    id: 8,
    name: 'Diya Mehta',
    email: 'diya.mehta@example.com',
    phone: '210-987-6543',
    role: 'Manager',
    address: '6789, Race Course Road, Coimbatore, India',
  },
  {
    id: 9,
    name: 'Karan Chawla',
    email: 'karan.chawla@example.com',
    phone: '109-876-5432',
    role: 'Customer',
    address: '7890, Rajpath, Gandhinagar, India',
  },
  {
    id: 10,
    name: 'Riya Kapoor',
    email: 'riya.kapoor@example.com',
    phone: '098-765-4321',
    role: 'Sub Admin',
    address: '8901, Sector 62, Noida, India',
  },
];
